FROM golang:1.22.2 as builder

WORKDIR /app

COPY . .

RUN go mod download

ARG NUM

WORKDIR /app/fulcrum

RUN go build -o main .

ENV N=$NUM

EXPOSE 50056
EXPOSE 50057
EXPOSE 50058

CMD ["sh", "-c", "./main $N"]