# Use the official Go image as the base image
FROM golang:1.22.2 

# Set the working directory inside the container
WORKDIR /app

# Copy the Go modules files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

# Change directory to the broker application
WORKDIR /app/broker

# Build the Go application
RUN go build -o main .

# Expose port 50051 to the outside world
EXPOSE 50051

# Command to run the executable
CMD ["./main"]